apps/blog/urls.py
from django.conf.urls import url
from apps.blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(\d+)/$', views.blog_view, name='blog_view'),
    url(r'^list/$', views.blog_list, name='list'),
    url(r'^add/$', views.blog_add, name='add'),
    url(r'^get_json_list/$', views.get_json_list, name="get_json_list"),
    url(r'^edit/(\d+)/$', views.blog_edit, name="edit"),

]

apps/comment/urls.py
from django.conf.urls import url
from apps.comment import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^captcha/$', views.captcha, name='captcha'),
    url(r'^(\d+)/$', views.comment, name='comment'),

]

loonblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.homepage.views import index
from apps.blog import urls as blog_urls
from apps.ueditor import urls as ueditor_urls
from apps.comment import urls as comment_urls
from apps.about import urls as about_urls
from apps.photo import urls as photo_urls
from apps.interest import urls as interest_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^blog/', include(blog_urls, namespace="blog")),
    url(r'^ueditor/', include(ueditor_urls, namespace="ueditor")),
    url(r'^comment/', include(comment_urls, namespace="comment")),
    url(r'^about/', include(about_urls, namespace="about")),
    url(r'^photo/', include(photo_urls, namespace="photo")),
    url(r'^interest/', include(interest_urls, namespace="interest")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """
    专题
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '专题'
        verbose_name_plural = '专题'



class Category(models.Model):
    """
    分类
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'



class Tag(models.Model):
    """
    标签
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'


class Blog(models.Model):
    """
    博客
    """
    title = models.CharField('名称', max_length=500)
    topic_id = models.IntegerField('主题id', null=True, blank=True)
    category_id = models.IntegerField('分类id')
    view_count = models.IntegerField('访问次数', default=0)   # 非实时更新，请求次数写入redis。 当redis值大于10时候再更新数据库

    content = models.TextField('内容')
    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)


class BlogTag(models.Model):
    """
    博客标签
    """
    blog_id = models.IntegerField('博客id')
    tag_id = models.IntegerField('标签id')

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

apps/blog/views.py
import json
import logging
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from django.db.models.query import QuerySet

from services.blog.blog_service import BlogService
from services.blog.blog_tag_service import BlogTagService
from services.blog.category_service import CategoryService
from services.blog.tag_service import TagService
from services.blog.topic_service import TopicService
# Create your views here.
from services.comment.comment_service import CommentService


@cache_page(300)
def index(request):
    """
    文章首页
    :param request:
    :return:
    """
    page = request.GET.get('page', 0)
    page = int(page) if page else ''
    cat = request.GET.get('cat', 0)
    cat = int(cat) if cat else ''


    if cat:
        blogs, msg = BlogService.get_blog_list_by_page(page, category_id=cat)
    else:
        blogs, msg = BlogService.get_blog_list_by_page(page)
    if blogs or isinstance(blogs, QuerySet):
        total_count = msg[0]
        total_page = int(msg[1])
    else:
        return HttpResponseServerError
    blog_list = []
    for blog in blogs:
        blog_dict = {}
        blog_dict['title'] = blog.title
        blog_dict['id'] = blog.id
        blog_dict['gmt_created'] = blog.gmt_created
        blog_dict['content'] = blog.content
        blog_dict['category'] = blog.category_id
        category_query, msg = CategoryService.get_category_by_id(blog.category_id)
        if category_query:
            blog_dict['category'] = category_query[0].name
        else:
            blog_dict['category'] = ''

        topic_query, msg = TopicService.get_topic_by_id(blog.topic_id)
        if topic_query:
            blog_dict['topic'] = topic_query[0].name
        else:
            blog_dict['topic'] = ''

        blog_tag_query, msg = BlogTagService.get_tag_obj_list_by_blog_id(blog.id)
        blog_dict['blog_tag_query'] = blog_tag_query
        blog_list.append(blog_dict)
    if not page:
        page = 1

    if page < total_page:
        has_next = True
    else:
        has_next = False
    if (page >= 2) and (total_page) >2:
        has_pre = True
    else:
        has_pre = False

    category_list_query, msg4 = CategoryService.get_category_list()
    tag_list_query, msg4 = TagService.get_tag_list()
    topic_list_query, msg4 = TopicService.get_topic_list()

    params = dict(blogs=blog_list, total_count=total_count, total_page=total_page, page=page,has_next=has_next,
                  has_pre=has_pre, category_list_query=category_list_query, tag_list_query=tag_list_query,
                  topic_list_query=topic_list_query, cat=cat)

    return render(request, 'blog/blog_index.html', params)


@login_required
@csrf_exempt  # 暂时通过exempt来支持ajax。后续有时间改下
def get_json_list(request):
    """
    json格式blog列表
    :param request:
    :return:
    """
    request_data = request.POST
    draw = request_data.get('draw', '')
    start = request_data.get('start', '')
    search_value = request_data.get('search[value]', '')
    length = request_data.get('length', '')

    query_contains = search_value

    query_control = dict(start=start, length=length)

    data, msg = BlogService.get_json_list(query_contains, query_control)

    return HttpResponse(json.dumps({"draw": draw, "recordsTotal": msg[1], "recordsFiltered": msg[2], "data": data}),
                            content_type='application/json')


# @cache_page(300) # 因为留言后刷新页面，用缓存的话 会导致页面不更新，暂时去掉
def blog_view(request, blog_id):
    """
    文章查看
    :param request:
    :param blog_id:
    :return:
    """
    BlogService.update_view_count(int(blog_id))
    blog_query, msg = BlogService.get_blog_by_id(blog_id, True)
    blog_dict = {}
    if blog_query:
        blog_dict['id'] = blog_query[0].id
        blog_dict['title'] = blog_query[0].title
        blog_dict['gmt_created'] = blog_query[0].gmt_created
        blog_dict['content'] = blog_query[0].content
        blog_dict['category_id'] = blog_query[0].category_id
        category_query, msg = CategoryService.get_category_by_id(blog_query[0].category_id)
        if category_query:
            blog_dict['category'] = category_query[0].name
        else:
            blog_dict['category'] = ''
        topic_query, msg = TopicService.get_topic_by_id(blog_query[0].topic_id)
        if topic_query:
            blog_dict['topic'] = topic_query[0].name
        else:
            blog_dict['topic'] = ''

        blog_tag_query, msg = BlogTagService.get_tag_obj_list_by_blog_id(blog_query[0].id)
        blog_dict['blog_tag_query'] = blog_tag_query
    else:
        return render(request, '404.html')
    category_list_query, msg4 = CategoryService.get_category_list()
    tag_list_query, msg4 = TagService.get_tag_list()
    topic_list_query, msg4 = TopicService.get_topic_list()

    comment_list_query, msg5 = CommentService().get_comment_by_blog_id(obj_id=blog_id)

    params = dict(blog=blog_dict, category_list_query=category_list_query, tag_list_query=tag_list_query,
                  topic_list_query=topic_list_query, comment_list_query=comment_list_query)


    return render(request, 'blog/blog_view.html', params)


@login_required
def blog_list(request):
    """
    博客管理列表
    :param request:
    :param id:
    :return:
    """
    return render(request, 'blog/blog_list.html')


@login_required
@require_http_methods(['GET', 'POST'])
def blog_add(request):
    """
    新增文章
    :param request:
    :return:
    """

    request_method = request.method
    if request_method == 'GET':
        category_list, msg1 = CategoryService.get_category_list()
        tag_list, msg2 = TagService.get_tag_list()
        topic_list, msg3 = TopicService.get_topic_list()
        params = dict(category_list=category_list, tag_list=tag_list, topic_list=topic_list, page_title='新增文章')
        params['post_url'] = '/blog/add/'
        return render(request, 'blog/blog_edit.html', params)
    elif request_method == 'POST':
        post_data = request.POST
        title = post_data.get('title', '')
        topic_id = post_data.get('topic', '')
        category_id = post_data.get('category', '')
        content = post_data.get('content', '')
        tag_id_list = post_data.getlist('tag', [])
        creator = request.user.username
        params = dict(title=title, topic_id=topic_id, category_id=category_id, content=content, tag_id_list=tag_id_list,
        creator=creator)
        flag, msg = BlogService.add_blog(params)
        if flag:
            return HttpResponseRedirect('/blog/list/')
        else:
            return HttpResponse('新增失败:{}'.format(msg))


@login_required
@require_http_methods(['GET', 'POST'])
def blog_edit(request, blog_id):
    """
    编辑文章
    :param request:
    :param blog_id:
    :return:
    """
    request_method =request.method
    category_list, msg1 = CategoryService.get_category_list()
    tag_list, msg2 = TagService.get_tag_list()
    topic_list, msg3 = TopicService.get_topic_list()
    params = dict(category_list=category_list, tag_list=tag_list, topic_list=topic_list, page_title='编辑文章')

    if request_method == 'GET':
        query_result, msg = BlogService.get_blog_by_id(blog_id)

        tag_query_list, msg1 = BlogTagService.get_tag_list_by_blog_id(blog_id)

        if query_result:
            params['query_result0'] = query_result[0]
            params['tag_query_list'] = tag_query_list
            params['post_url'] = '/blog/edit/{}/'.format(blog_id)
            return render(request, 'blog/blog_edit.html', params)
        else:
            return HttpResponse('Error:文章不存在')

    else:
        post_data = request.POST
        title = post_data.get('title', '')
        topic_id = post_data.get('topic', '')
        category_id = post_data.get('category', '')
        content = post_data.get('content', '')
        tag_id_list = post_data.getlist('tag', [])
        creator = request.user.username
        params = dict(title=title, topic_id=topic_id, category_id=category_id, content=content, tag_id_list=tag_id_list,
                      blog_id=blog_id, creator=creator)
        flag, msg = BlogService.edit_blog(params)
        if flag:
            return HttpResponseRedirect('/blog/list/')
        else:
            return HttpResponse('编辑失败:{}'.format(msg))

templates/blog/includes/blogbox.html
<div class="blogBox fltlft">
	<div class="topBox">
    	<div class="timeBox fltlft enFont textCenter">
            <span class="fs2" id="time_month">{{ blog.gmt_created|date:"d MY" }}</span>
        </div>
        <div class="infoBox fltrt">
        	<div class="fs26 bg1" id="blog_title">
            	<a class="normDecorA" href="/blog/{{ blog.id }}/">{{ blog.title }}</a>
            </div>
            <div class="fs14 bg2" id="blog_ct">
            	<span class="fltlft" id="blog_cate"><a class="blueA" href="?cat={{ blog.category_id }}">{{ blog.category }}</a></span>
            	<span class="fltlft" id="blog_cate"><a class="blueA" href="?cat={{ blog.topic_id }}">{{ blog.topic}}</a></span>
                <span class="fltlft" id="blog_tags">
                	{% for blog_tag_query0 in blog.blog_tag_query %}
                		<a class="blueA" href="?tag={{ blog_tag_query0.tag_id}}">{{ blog_tag_query0.tag_name }}</a>
                	{% endfor %}
                </span>
                <span class="clearfloat"></span>
            </div>
        </div>
        <div class="clearfloat"></div>
    </div>
    <div class="contentBox bg1">

    	{{ blog.content|safe }}
    </div>
    {% if relates %}
	    <div class="blog_topic bg2">
	    	<div class="left_title textCenter">
	        	<span class="fs18 enFont">TOPIC</span>
	        </div>
	        <div class="blogs_in_topic fltrt bg1">
	        	<ul class="blog_list fs14">
	        		{% for blog in relates %}
		            	<li><a class="blueA" href="{% url 'blog:blog_view' blog.id %}">{{ blog.title }}</a></li>
	        		{% endfor %}
	            </ul>
	        </div>
	        <div class="clearfloat"></div>
	    </div>
	{% endif %}
</div>

templates/blog/includes/cmtdisplaybox.html
<div class="comment bg2" id="cmt_box_{{ comment_query.id }}">
	<div class="commentatorInfo bg2">
    	<div class="fltlft">
        	<img class="ctavatar" src="/static/image/davatar.png" width="63" height="63">
        </div>
        <div class="fs14 fltlft">
        	<span class="cmtInfo"><a class="blueA commentator" href="javascript:void(0)" onclick="replay_comment('{{ comment_query.id }}','{{ comment_query.name }}')" data-id="{{ comment_query.id }}" title="点击回复TA的留言">{{ comment_query.name }}</a> 发表于 {{ comment_query.gmt_created|date:"Y-n-j H:i" }}</span>
        </div>
        <div class="clearfloat"></div>
    </div>
    <div class="cmtContent fs14 bg1">
        <span>{{ comment_query.content|linebreaks }}</span>
    </div>
    {% for reply in comment_query.get_replys %}
	    {% include "blog/includes/replydisplaybox.html" %}
    {% endfor %}
</div>

templates/blog/includes/cmtformbox.html
<div class="cmtInputBox fltlft">
	<div id="cmtTitle">
    	<span class="fs24">您来留言：</span>
    </div>
    <div class="cmtForm bg1 fltlft">
        <div class="bg2" id="cutting_line"></div>
        <div class="bg1" id="contact_form_box">
            <form class="form-horizontal" name="comment_form" id="comment_form"
                                  role="form" enctype="multipart/form-data" action="{% url 'comment:comment' blog.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-xs-1 control-label" for="name"><i style="color: red">*</i></label>
            <div class="col-xs-6 align-left">
                <input required type="text" class="form-control required" name="name" id="name"
                       placeholder="您的称呼">
            </div>
            <div class="col-xs-5">
                <div id="replay_coment_alert"></div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-1 control-label" for="email"><i style="color: red">*</i></label>
            <div class="col-xs-6 align-left">
                <input required type="text" class="form-control required" name="email" id="email"
                       placeholder="您的邮箱">
            </div>
        </div>
        <div id="other_input">
        </div>

        <div class="form-group">
            <label class="col-xs-1 control-label" for="captcha"><i style="color: red">*</i></label>
            <div class="col-xs-6 align-left">
                <input required type="text" class="form-control required" name="captcha" id="captcha"
                       placeholder="请输入右边的验证码" >
            </div>
            <img onclick="this.setAttribute('src','/comment/captcha/?nocache='+Math.random());" src="/comment/captcha/" alt="Captcha"/>
        </div>


        <div class="form-group">
            <label class="col-xs-1 control-label" for="comment_content"><i style="color: red">*</i></label>
            <div class="col-xs-11 align-left">
                <textarea class="form-control" name="comment_content" id="comment_content" rows="5" placeholder="期待您的留言"></textarea>
            </div>
        </div>


        <div class="modal-footer">
            <input type="button" class="btn btn-success" onclick="submit_comment();" value="提交"></input>
        </div>
    </form>




        </div>
    </div>
</div>

<script type="application/javascript">

    function submit_comment() {
{#        var name = document.getElementById('name').value;#}
{#        var email = document.getElementById('email').value;#}
{#        var captcha = document.getElementById('captcha').value;#}
{#        var is_recomment = document.getElementById('is_recomment').value;#}
        var name = $('#name').val();
        var email = $('#email').val();
        var captcha = $('#captcha').val();
        var is_recomment = $('#is_recomment').val();
        var comment_content = $('#comment_content').val();
{#        var comment_content = document.getElementById('comment_content').value;#}
        if (name == ""){
            alert('请填写你的称呼');
            $("#name").focus();
            return false;
        }
        if (email== ""|| ( email!="" && !/.+@.+\.[a-zA-Z]{2,4}$/.test(email) ) ){
            alert('请填写正确的邮箱');
            $("#email").focus();
            return false;
        }
        if (captcha== ""){
            alert('请填写验证码');
            $("#captcha").focus();
            return false;
        }
        if (comment_content== ""){
            alert('请填写内容');
            $("#comment_content").focus();
            return false;
        }
        $.ajax({
            type:"POST",
            dataType:"json",
            url:"/comment/{{blog.id}}/",
            data : {
                'csrfmiddlewaretoken':getCookie('csrftoken'),
                'name':name,
                'email':email,
                'captcha':captcha,
                'comment_content':comment_content,
                'is_recomment':is_recomment,
            },
            success:function (data) {
                if(data.code==200){
                    alert('留言成功');
                    window.location.reload();
                }
                else if(data.code==500){
                    alert(data.msg);
                }
                else{
                    alert('发送未知错误,留言失败');
                }

            }
        })

    }

    function replay_comment(id, name) {
        var input_str = '<input type="text" name="is_recomment" id="is_recomment" hidden="hidden" value="' + id + '">';
        $('#other_input').html(input_str);
        var replay_coment_alert_str = '<p style="color:#1d8dcd">正在回复'+ name + '的留言...(取消)</p>';
        var replay_coment_alert_str = '<p style="color:#1d8dcd">正在回复'+ name + '的留言...' +
            '<a href="javascript:void(0)" onclick="cancel_replay_comment()">(取消)</>' + '</p>';
        $('#replay_coment_alert').html(replay_coment_alert_str);
        $('#name').focus();
    }

    function cancel_replay_comment() {
        $('#other_input').empty();
        $('#replay_coment_alert').empty();

    }
</script>

templates/blog/includes/paginator.html
<div class="paginator fltlft textRight" id="blog_paginator">
    {% if cat %}
        {% if has_pre %}
            <a class="pageItem" href="/blog/?page=1&cat={{ cat }}"><<</a>
            <a class="pageItem" href="/blog/?page={{ page|add:-1 }}&cat={{ cat }}"><</a>
        {% endif %}
        {% if page < total_page %}
            <a class="pageItem" href="/blog/?page=1&cat={{ cat }}">{{ page }}</a>
        {% endif %}

        {% if has_next %}
            <a class="pageItem" href="/blog/?page={{ page|add:1 }}&cat={{ cat }}">></a>
            <a class="pageItem" href="/blog/?page={{ total_page }}&cat={{ cat }}">>> </a>
        {% endif %}
    {% else %}
        {% if has_pre %}
            <a class="pageItem" href="/blog/?page=1"><<</a>
            <a class="pageItem" href="/blog/?page={{ page|add:-1 }}"><</a>
        {% endif %}
        {% if page < total_page %}
            <a class="pageItem" href="/blog/?page=1">{{ page }}</a>
        {% endif %}

        {% if has_next %}
            <a class="pageItem" href="/blog/?page={{ page|add:1 }}">></a>
            <a class="pageItem" href="/blog/?page={{ total_page }}">>> </a>
        {% endif %}
    {% endif %}


</div>

templates/blog/includes/replydisplaybox.html
<div class="{% cycle 'replyBoxOdd' 'replyBoxEven bg2' %}">
    <div class="replyContent {% cycle 'fltlft' 'fltrt' %} fs14">
        <span><a class="blueA commentator" href="javascript:void(0)" onclick="replay_comment('{{ reply.id}}','{{ reply.name  }}')" title="点击回复TA的留言">{{ reply.name }}</a> 回复说：{{ reply.content|linebreaksbr }}</span>
    </div>
    <div class="replyerAvatar {% cycle 'fltrt' 'fltlft' %}">
        <img class="ctavatar" src="/static/image/davatar.png" width="63" height="63">
    </div>
    <div class="clearfloat"></div>
</div>

templates/blog/includes/sidebar.html
{% load staticfiles %}

<div class="fltrt sidebar">
{#	<div class="searchBox">#}
{#    	<form action="" method="get" id="search_form">#}
{#    		<input class="xnorminput" id="search" name="search" type="text" placeholder="搜索文章" disabled />#}
{#        </form>#}
{#        <div class="searchIcon" onclick="document.getElementById('search_form').submit();"id="search_icon"></div>#}
{#    </div>#}
    <div class="listBox2 mt37">
        <ul>
            <li class="listTitle textCenter">CATEGORIES</li>
            {% for category_list_query0 in category_list_query %}
            	<a href="/blog/?cat={{ category_list_query0.id }}"><li class="listItem fltlft textCenter">{{ category_list_query0.name }}</li></a>
            {% endfor %}
            <li class="clearfloat"></li>
        </ul>
    </div>

    <div class="tagBox mt37">
    	<div class="title textCenter">TOPICS</div>
        <div class="tags textCenter">
        	{% for topic_query in topic_list_query %}
        		<a class="tagItem" href="/blog/?topic={{ topic_query.id }}">{{ topic_query.name }}</a>
        	{% endfor %}
        </div>
    </div>


</div>