apps/blog/urls.py
from django.conf.urls import url
from apps.blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(\d+)/$', views.blog_view, name='blog_view'),
    url(r'^list/$', views.blog_list, name='list'),
    url(r'^add/$', views.blog_add, name='add'),
    url(r'^get_json_list/$', views.get_json_list, name="get_json_list"),
    url(r'^edit/(\d+)/$', views.blog_edit, name="edit"),

]

loonblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.homepage.views import index
from apps.blog import urls as blog_urls
from apps.ueditor import urls as ueditor_urls
from apps.comment import urls as comment_urls
from apps.about import urls as about_urls
from apps.photo import urls as photo_urls
from apps.interest import urls as interest_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^blog/', include(blog_urls, namespace="blog")),
    url(r'^ueditor/', include(ueditor_urls, namespace="ueditor")),
    url(r'^comment/', include(comment_urls, namespace="comment")),
    url(r'^about/', include(about_urls, namespace="about")),
    url(r'^photo/', include(photo_urls, namespace="photo")),
    url(r'^interest/', include(interest_urls, namespace="interest")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """
    专题
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '专题'
        verbose_name_plural = '专题'



class Category(models.Model):
    """
    分类
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'



class Tag(models.Model):
    """
    标签
    """
    name = models.CharField('名称', max_length=50)

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'


class Blog(models.Model):
    """
    博客
    """
    title = models.CharField('名称', max_length=500)
    topic_id = models.IntegerField('主题id', null=True, blank=True)
    category_id = models.IntegerField('分类id')
    view_count = models.IntegerField('访问次数', default=0)   # 非实时更新，请求次数写入redis。 当redis值大于10时候再更新数据库

    content = models.TextField('内容')
    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)


class BlogTag(models.Model):
    """
    博客标签
    """
    blog_id = models.IntegerField('博客id')
    tag_id = models.IntegerField('标签id')

    creator = models.CharField('创建人', max_length=50)
    gmt_created = models.DateTimeField('创建时间', auto_now_add=True, help_text="")
    gmt_modified = models.DateTimeField('修改时间', auto_now=True, help_text="")
    is_deleted = models.BooleanField('已删除', default=False)

apps/blog/views.py
import json
import logging
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from django.db.models.query import QuerySet

from services.blog.blog_service import BlogService
from services.blog.blog_tag_service import BlogTagService
from services.blog.category_service import CategoryService
from services.blog.tag_service import TagService
from services.blog.topic_service import TopicService
# Create your views here.
from services.comment.comment_service import CommentService


@cache_page(300)
def index(request):
    """
    文章首页
    :param request:
    :return:
    """
    page = request.GET.get('page', 0)
    page = int(page) if page else ''
    cat = request.GET.get('cat', 0)
    cat = int(cat) if cat else ''


    if cat:
        blogs, msg = BlogService.get_blog_list_by_page(page, category_id=cat)
    else:
        blogs, msg = BlogService.get_blog_list_by_page(page)
    if blogs or isinstance(blogs, QuerySet):
        total_count = msg[0]
        total_page = int(msg[1])
    else:
        return HttpResponseServerError
    blog_list = []
    for blog in blogs:
        blog_dict = {}
        blog_dict['title'] = blog.title
        blog_dict['id'] = blog.id
        blog_dict['gmt_created'] = blog.gmt_created
        blog_dict['content'] = blog.content
        blog_dict['category'] = blog.category_id
        category_query, msg = CategoryService.get_category_by_id(blog.category_id)
        if category_query:
            blog_dict['category'] = category_query[0].name
        else:
            blog_dict['category'] = ''

        topic_query, msg = TopicService.get_topic_by_id(blog.topic_id)
        if topic_query:
            blog_dict['topic'] = topic_query[0].name
        else:
            blog_dict['topic'] = ''

        blog_tag_query, msg = BlogTagService.get_tag_obj_list_by_blog_id(blog.id)
        blog_dict['blog_tag_query'] = blog_tag_query
        blog_list.append(blog_dict)
    if not page:
        page = 1

    if page < total_page:
        has_next = True
    else:
        has_next = False
    if (page >= 2) and (total_page) >2:
        has_pre = True
    else:
        has_pre = False

    category_list_query, msg4 = CategoryService.get_category_list()
    tag_list_query, msg4 = TagService.get_tag_list()
    topic_list_query, msg4 = TopicService.get_topic_list()

    params = dict(blogs=blog_list, total_count=total_count, total_page=total_page, page=page,has_next=has_next,
                  has_pre=has_pre, category_list_query=category_list_query, tag_list_query=tag_list_query,
                  topic_list_query=topic_list_query, cat=cat)

    return render(request, 'blog/blog_index.html', params)


@login_required
@csrf_exempt  # 暂时通过exempt来支持ajax。后续有时间改下
def get_json_list(request):
    """
    json格式blog列表
    :param request:
    :return:
    """
    request_data = request.POST
    draw = request_data.get('draw', '')
    start = request_data.get('start', '')
    search_value = request_data.get('search[value]', '')
    length = request_data.get('length', '')

    query_contains = search_value

    query_control = dict(start=start, length=length)

    data, msg = BlogService.get_json_list(query_contains, query_control)

    return HttpResponse(json.dumps({"draw": draw, "recordsTotal": msg[1], "recordsFiltered": msg[2], "data": data}),
                            content_type='application/json')


# @cache_page(300) # 因为留言后刷新页面，用缓存的话 会导致页面不更新，暂时去掉
def blog_view(request, blog_id):
    """
    文章查看
    :param request:
    :param blog_id:
    :return:
    """
    BlogService.update_view_count(int(blog_id))
    blog_query, msg = BlogService.get_blog_by_id(blog_id, True)
    blog_dict = {}
    if blog_query:
        blog_dict['id'] = blog_query[0].id
        blog_dict['title'] = blog_query[0].title
        blog_dict['gmt_created'] = blog_query[0].gmt_created
        blog_dict['content'] = blog_query[0].content
        blog_dict['category_id'] = blog_query[0].category_id
        category_query, msg = CategoryService.get_category_by_id(blog_query[0].category_id)
        if category_query:
            blog_dict['category'] = category_query[0].name
        else:
            blog_dict['category'] = ''
        topic_query, msg = TopicService.get_topic_by_id(blog_query[0].topic_id)
        if topic_query:
            blog_dict['topic'] = topic_query[0].name
        else:
            blog_dict['topic'] = ''

        blog_tag_query, msg = BlogTagService.get_tag_obj_list_by_blog_id(blog_query[0].id)
        blog_dict['blog_tag_query'] = blog_tag_query
    else:
        return render(request, '404.html')
    category_list_query, msg4 = CategoryService.get_category_list()
    tag_list_query, msg4 = TagService.get_tag_list()
    topic_list_query, msg4 = TopicService.get_topic_list()

    comment_list_query, msg5 = CommentService().get_comment_by_blog_id(obj_id=blog_id)

    params = dict(blog=blog_dict, category_list_query=category_list_query, tag_list_query=tag_list_query,
                  topic_list_query=topic_list_query, comment_list_query=comment_list_query)


    return render(request, 'blog/blog_view.html', params)


@login_required
def blog_list(request):
    """
    博客管理列表
    :param request:
    :param id:
    :return:
    """
    return render(request, 'blog/blog_list.html')


@login_required
@require_http_methods(['GET', 'POST'])
def blog_add(request):
    """
    新增文章
    :param request:
    :return:
    """

    request_method = request.method
    if request_method == 'GET':
        category_list, msg1 = CategoryService.get_category_list()
        tag_list, msg2 = TagService.get_tag_list()
        topic_list, msg3 = TopicService.get_topic_list()
        params = dict(category_list=category_list, tag_list=tag_list, topic_list=topic_list, page_title='新增文章')
        params['post_url'] = '/blog/add/'
        return render(request, 'blog/blog_edit.html', params)
    elif request_method == 'POST':
        post_data = request.POST
        title = post_data.get('title', '')
        topic_id = post_data.get('topic', '')
        category_id = post_data.get('category', '')
        content = post_data.get('content', '')
        tag_id_list = post_data.getlist('tag', [])
        creator = request.user.username
        params = dict(title=title, topic_id=topic_id, category_id=category_id, content=content, tag_id_list=tag_id_list,
        creator=creator)
        flag, msg = BlogService.add_blog(params)
        if flag:
            return HttpResponseRedirect('/blog/list/')
        else:
            return HttpResponse('新增失败:{}'.format(msg))


@login_required
@require_http_methods(['GET', 'POST'])
def blog_edit(request, blog_id):
    """
    编辑文章
    :param request:
    :param blog_id:
    :return:
    """
    request_method =request.method
    category_list, msg1 = CategoryService.get_category_list()
    tag_list, msg2 = TagService.get_tag_list()
    topic_list, msg3 = TopicService.get_topic_list()
    params = dict(category_list=category_list, tag_list=tag_list, topic_list=topic_list, page_title='编辑文章')

    if request_method == 'GET':
        query_result, msg = BlogService.get_blog_by_id(blog_id)

        tag_query_list, msg1 = BlogTagService.get_tag_list_by_blog_id(blog_id)

        if query_result:
            params['query_result0'] = query_result[0]
            params['tag_query_list'] = tag_query_list
            params['post_url'] = '/blog/edit/{}/'.format(blog_id)
            return render(request, 'blog/blog_edit.html', params)
        else:
            return HttpResponse('Error:文章不存在')

    else:
        post_data = request.POST
        title = post_data.get('title', '')
        topic_id = post_data.get('topic', '')
        category_id = post_data.get('category', '')
        content = post_data.get('content', '')
        tag_id_list = post_data.getlist('tag', [])
        creator = request.user.username
        params = dict(title=title, topic_id=topic_id, category_id=category_id, content=content, tag_id_list=tag_id_list,
                      blog_id=blog_id, creator=creator)
        flag, msg = BlogService.edit_blog(params)
        if flag:
            return HttpResponseRedirect('/blog/list/')
        else:
            return HttpResponse('编辑失败:{}'.format(msg))

templates/blog/blog_base.html
{% extends "base.html" %}
{% block nav_2 %}focus{% endblock %}
{% load staticfiles %}

{% block extra_link %}
	<link href="{% static 'css/blog.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'syntaxhighlighter/css/shCore.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'syntaxhighlighter/css/shThemeDefault.css' %}" type="text/css" rel="stylesheet">
	{% block inner_extra_link %}{% endblock %}
{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/placeholder.js' %}"></script>
	<script src="{% static 'syntaxhighlighter/js/XRegExp.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shCore.js' %}" type="text/javascript"></script>
	<script src="{% static 'syntaxhighlighter/js/shAutoloader.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/syntaxhighlighter_autoloads.js' %}" type="text/javascript"></script>
{% endblock %}
{#{% block inner_extra_js %}{% endblock %}#}

templates/blog/blog_edit.html
{% extends "blog/blog_base.html" %}
{% load staticfiles %}

{% block title %}{{ page_title }}{% endblock %}
{% block extra_link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-multiselect.css' %}" >

{% endblock %}




{% block container %}
    <div class="blogeditBox">
    <form class="form-horizontal" name="blog_edit_form" id="blog_edit_form"
{#                                  role="form" enctype="multipart/form-data" action="/blog/add/" method="post">#}
                                  role="form" enctype="multipart/form-data" action="{{ post_url }}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">标题<i style='color:red'>*</i></label>
            <div class="col-xs-10 align-left">
                <input required type="text" class="form-control required" name="title"
                       placeholder="请输入文章标题" value = {{ query_result0.title }}>
            </div>
        </div>

        <div class="form-group">
            <label for="topic" class="col-sm-1 col-sm-offset-1 control-label">主题<i style='color:red'>*</i></label>
            <div class="col-xs-5 align-left">
                <select class="form-control select2 required" id="topic" name="topic"
                        data-placeholder="选择主题" style="width: 100%;">
                    {% if topic_list %}
                    {% for topic in topic_list %}
                        {% ifequal query_result0.topic_id topic.id %}
                        <option value="{{ topic.id }}" selected>{{ topic.name }}</option>
                        {% else %}
                    <option value="{{ topic.id }}" >{{ topic.name }}</option>
                        {% endifequal %}
                    {% endfor %}
                    {% endif %}
                </select>
            </div>

            <label for="category" class="col-sm-1 control-label">分类<i style='color:red'>*</i></label>
            <div class="col-xs-4 align-left">
                <select class="form-control select2 required" id="category" name="category"
                        data-placeholder="选择初始状态" style="width: 100%;">
                    {% if category_list %}
                    {% for category in category_list %}
                    {% ifequal query_result0.category_id category.id %}
                    <option value="{{ category.id }}" selected >{{ category.name }}</option>
                    {% else %}
                    <option value="{{ category.id }}" >{{ category.name }}</option>
                    {% endifequal %}
                    {% endfor %}
                    {% endif %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="tag" class="col-sm-2 control-label">标签<i style='color:red'>*</i></label>
            <div class="col-xs-10 align-left">
                <select class="multiselect required" id="tag" name="tag" multiple="multiple" style="width: 600px">
                  {% if tag_list %}
                    {% for tag in tag_list %}
                    {% if tag.id in tag_query_list %}
                        <option value="{{ tag.id }}" selected>{{ tag.name }}</option>
                    {% else %}
                    <option value="{{ tag.id }}" >{{ tag.name }}</option>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                </select>

            </div>
        </div>


        <div class="form-group">
            <label for="content" class="col-sm-2 control-label">内容</label>
            <div class="col-xs-10 align-left">
                <script id="content" name="content" type="text/plain">
                    {{ query_result0.content|safe }}
                </script>

            </div>
        </div>


        <div class="modal-footer">
            <button type="submit" class="btn btn-success">保存</button>
        </div>
    </form>
    </div>



{% endblock %}

{% block inner_extra_js %}
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-multiselect.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>

    <script type="text/javascript">
        var editor = new UE.ui.Editor({initialFrameHeight:300,initialFrameWidth:1024 });
        editor.render("content");
        $('.multiselect').multiselect({
            maxHeight: 500,
            enableFiltering: true,
            buttonWidth: '1000px',
            filterBehavior: 'value'});

        $().ready(function() {
         $("#blog_edit_form").validate();
        });
    </script>

{% endblock %}

templates/blog/blog_index.html
{% extends "blog/blog_base.html" %}
{% load staticfiles %}

{% block inner_extra_js %}
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
{#	<script src="{% static 'js/index.js' %}"></script>#}
	<script>
		(function($){
			$.getUrlParam = function(name){
				var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
				var r = window.location.search.substr(1).match(reg);
				if (r!=null) return unescape(r[2]); return null;
			}
		})(jQuery);
		$(document).ready(function(){
			key = $.getUrlParam('search');
			if (key){
				var hl = new Highlighter();
				nodes = $('.contentBox').find('p');
				for (var i=0; i < nodes.length;i++){
				    hl.highlight(nodes[i], key);
				}
			}
		});
	</script>
{% endblock %}

{% block container %}
	<div class="normBox">
    	{% include "blog/includes/sidebar.html" %}
        {% for blog in blogs %}
    		{% include "blog/includes/blogbox.html" %}
    	{% endfor %}
{#    	{% if page_instance.has_other_pages %}#}
 			{% include "blog/includes/paginator.html" %}
{# 		{% endif %}#}
        <div class="clearfloat"></div>
	<!-- end blog_box --></div>
    <div class="clearfloat"></div>
{% endblock %}

templates/blog/blog_list.html
{% extends "blog/blog_base.html" %}
{% load staticfiles %}

{% block title %}文章管理{% endblock %}
{% block extra_link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap.min.css' %}" >

{% endblock %}

{% block container %}
    <div class="blogadminBox">
    <a href="/blog/add/" role="button" class="btn btn-success" data-toggle="modal">新增</a>
    <table id="blog_table" class="table table-striped table-bordered dataTable no-footer">
    <thead>
        <tr>
            <th>标题</th>
            <th style="width: 10%">分类</th>
            <th style="width: 15%">标签</th>
            <th style="width: 8%">评论数</th>
            <th style="width: 8%">已删除</th>
            <th style="width: 15%">创建时间</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>
    </div>



{% endblock %}

{% block inner_extra_js %}
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready( function () {
          $('#blog_table').DataTable({
          "processing":true,
          "serverSide":true,
          "bFilter":true,
          "ordering":false,
          "language": {
              "searchPlaceholder":'标题及内容模糊查询',
            },
          "ajax":{
              "url": "{% url 'blog:get_json_list' %}",
              "type": "POST",
{#              "data":function (d) {#}
{#                  d.username= document.getElementById("username").value;#}
{#                  d.chinese_name = document.getElementById('chinese_name').value;;#}
{#                  d.query_year = document.getElementById('query_year').value;#}
{#                  d.query_month = document.getElementById('query_month').value;#}
{#              }#}
          },
          "columns":
          [{"data":"title"},
          {"data":"category"},
          {"data":"tag"},
          {"data":"comment_times"},
          {"data":"is_deleted"},
          {"data":"gmt_created"},]

        });
            } );
    </script>



{% endblock %}

templates/blog/blog_view.html
{% extends "blog/blog_base.html" %}
{% load staticfiles %}


{% block inner_extra_link %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
{% endblock %}

{% block inner_extra_js %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/loonapp.js' %}"></script>
{% endblock %}

{% block title %}{{ blog.title }} - 文章详情 - Loonapp{% endblock %}
{% block meta_desc %}{{ blog.title }}: {{ blog.content|striptags|truncatechars:100 }}{% endblock %}
{#{% block meta_keywords %}{{ blog_dict.tag_list|join:"," }}{% endblock %}#}

{% block container %}
	<div class="normBox">
		{% include "blog/includes/sidebar.html" %}
    	{% include "blog/includes/blogbox.html" %}
        {% if comment_list_query %}
        <div class="cmtBox fltlft">
            <div id="cmtTitle">
                <span class="fs24">有<span id="cmt_count">{{ comment_list_query.count }}</span>条留言：</span>
            </div>
            {% for comment_query in comment_list_query %}
                {% include "blog/includes/cmtdisplaybox.html" %}
            {% endfor %}
        </div>
        {% endif %}
        <div id="new_cmt">

        </div>

        {% include "blog/includes/cmtformbox.html" %}
        <div class="clearfloat"></div> 
	<!-- end blog_box --></div>
    <div class="clearfloat"></div>
{% endblock %}

{% block popup %}
	<div class="popupBox" style="display: none;">
		<div class="popupLayout"></div>
		<div class="errorMessage">
			<div class="mainBox">
		        <div class="errorTitle fs24">
		            <span id="error_title"></span>
		  		</div>
		        <div class="errorDetail fs16">
		        	<span id="error_msg"></span>
		        </div>
		        <div class="btnBox textRight">
		        	<button class="writeBtn" id="error_confirm">确定</button>
		        </div>
		    </div>
		</div>
	</div>
{% endblock %}